{% set name = "autogluon.core" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 42e4838bb95328cedb54a9d094072068d8ce1e610a1154f91190b3670011561b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./core -vv
  number: 0
  script_env:
    - RELEASE=1

requirements:
  # adds osx_arm64 builds. See https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.25,<2.4.0                    # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
  # see https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
  run:
    - python >={{ python_min }},<3.13
    - numpy >=1.25,<2.4.0
    - scipy >=1.5.4,<1.17
    - scikit-learn >=1.4.0,<1.8.0  
    - networkx >=3.0,<4
    - pandas >=2.0.0,<2.4.0
    - tqdm >=4.38,<5
    - requests
    - matplotlib >=3.7.0,<3.11
    - boto3 >=1.10,<2
    - autogluon.common =={{ version }}
    - ray-default >=2.10.0,<2.45  # increase upper bound due to 2.10 not discoverable by osx py310
    - ray-tune >=2.10.0,<2.45  # increase upper bound due to 2.10 not discoverable by osx py310 
    - hyperopt >=0.2.7,<0.2.8 

test:
  imports:
    - autogluon.core
  commands:
    - python -c "from autogluon.common import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.core
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - suzhoum
    - tonyhoo
    - Innixma
    - prateekdesai04
