{% set name = "autogluon.core" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d1d357c154ad8deee5614f950ad07ee68ac2f65b8f3af114c1ee93c819934f1b

build:
  # noarch: python
  skip: true  # [py>=311]
  script: {{ PYTHON }} -m pip install ./core -vv
  number: 0
  script_env:
   - RELEASE=1

requirements:
  # adds osx_arm64 builds. See https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21,<1.27                    # [build_platform != target_platform]
  host:
    - python # >=3.8,<3.11
    - pip
  # see https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
  run:
    - python # >=3.8,<3.11
    - boto3 >=1.10,<2
    - numpy >=1.21,<1.27
    - pandas >=1.4.1,<1.6
    - scikit-learn >=1.0,<1.3
    - scipy >=1.5.4,<1.12
    - psutil >=5.7.3,<6
    - networkx >=3.0,<4
    - tqdm >=4.38,<5
    - pillow >=9.3,<9.6
    - requests
    - matplotlib-base
    - ray-default >=2.3,<2.4  # [not osx]
    - autogluon.common =={{ version }}

test:
  imports:
    - autogluon.core
  commands:
    - python -c "from autogluon.core import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.core
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
