github:
  branch_name: main
  tooling_branch_name: main
conda_forge_output_validation: true
bot:
  automerge: true
  inspection: update-grayskull
build_platform:
  osx_arm64: osx_64
test: native_and_emulated
